### INDEX MOVIE

GET http://localhost:3000/movies

### SHOW MOVIE

GET http://localhost:3000/movies/1

###  POST MOVIE

POST http://localhost:3000/movies
Content-type: application/json

{
  "title": "Speed",
  "year": 1994,
  "plot": "Where a bomb is a speed demon."
}

### PATCH MOVIE

PATCH http://localhost:3000/movies/11
Content-type: application/json

{
  "title": "Forrest Gump",
  "plot": "The story of the most serendipitous man on Earth."
}

### DELETE MOVIE

DELETE http://localhost:3000/movies/11

### SHOW ACTOR

GET http://localhost:3000/actors/11

### INDEX ACTOR

GET http://localhost:3000/actors

### POST ACTOR

POST http://localhost:3000/actors
Content-type: application/json

{
  "first_name": "Tommy",
  "last_name": "Wiseau",
  "known_for": "The Room"
}

### PATCH ACTOR

PATCH http://localhost:3000/actors/11
Content-Type: application/json

{
  "first_name": "Thomas"
}

### DELETE ACTOR

DELETE http://localhost:3000/actors/11